export enum ContentType {
    JSON = "application/json",
    TEXT = "text/plain",
    HTML = "text/html",
    XML = "application/xml",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    MULTIPART_FORM_DATA = "multipart/form-data",
    JAVASCRIPT = "application/javascript",
    CSS = "text/css",
    CSV = "text/csv",
    PDF = "application/pdf",
    ZIP = "application/zip",
    GZIP = "application/gzip",
    JPEG = "image/jpeg",
    PNG = "image/png",
    GIF = "image/gif",
    SVG = "image/svg+xml",
    WEBP = "image/webp",
    MP3 = "audio/mpeg",
    MP4 = "video/mp4",
    OGG = "audio/ogg",
    WAV = "audio/wav",
    WEBM = "video/webm"
  }  